#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /login
  controller: App\Controller\LoginController::index

logout:
  path: /login/logout
  controller: App\Controller\LoginController::logout

home_index:
  path: /home
  controller: App\Controller\HomeController::index

home_busqueda:
  path: /home/busqueda
  controller: App\Controller\HomeController::busqueda

sign_up:
  path: /usuario/new
  controller: App\Controller\UsuarioController::new