index:
  path: /home
  controller: App\Controller\HomeController::index

cita_edit:
  path: /cita/{id}/edit
  controller: App\Controller\CitaController::edit

cita_show:
  path: /cita/show/{id}
  controller: App\Controller\CitaController::show
    
cita_new:
  path: /cita/new/{convocado}
  controller: App\Controller\CitaController::new

cita_ajaxGetCitas:
  path: /cita/ajax/ajaxGetCitas/{id}
  controller: App\Controller\CitaController::ajaxGetCitas

cita_ajaxGetLocalizacion:
  path: /cita/ajax/ajaxGetLocalizacion/{id}
  controller: App\Controller\CitaController::ajaxGetLocalizacion

favorito_new:
  path: /favorito/new/{idInmueble}
  controller: App\Controller\FavoritoController::new

favorito_delete:
  path: /favorito/delete/{id}/{idInmueble}
  controller: App\Controller\FavoritoController::delete

favorito_index:
  path: /favorito/index/{idUsuario}
  controller: App\Controller\FavoritoController::index

alerta_new:
  path: /alerta/new/{idInmueble}
  controller: App\Controller\AlertaController::new

alerta_delete:
  path: /alerta/delete/{id}/{idInmueble}
  controller: App\Controller\AlertaController::delete

login:
  path: /login
  controller: App\Controller\LoginController::index

logout:
  path: /login/logout
  controller: App\Controller\LoginController::logout

home_index:
  path: /home
  controller: App\Controller\HomeController::index

home_busqueda:
  path: /home/busqueda
  controller: App\Controller\HomeController::busqueda

home_resultado:
  path: /home/resultado/{id}
  controller: App\Controller\HomeController::resultado

home_ajaxGetLocalizacion:
  path: /home/ajax/ajaxGetLocalizacion/{id}
  controller: App\Controller\HomeController::ajaxGetLocalizacion
  methods: [POST]
  
home_ajaxGetInmuebles:
  path: /home/ajax/ajaxGetInmuebles
  controller: App\Controller\HomeController::ajaxGetInmuebles
  methods: [POST]

sign_up:
  path: /usuario/new
  controller: App\Controller\UsuarioController::new

usuario_edit:
    path: /usuario/{id}/edit
    controller: App\Controller\UsuarioController::edit

inmueble_show:
  path: /inmueble/show/{id}
  controller: App\Controller\InmuebleController::show

inmueble_new:
  path: /inmueble/new
  controller: App\Controller\InmuebleController::new

inmobiliaria_new:
  path: /inmobiliaria/new/{id}
  controller: App\Controller\InmobiliariaController::new
  requirements:
    id: '\d+'

  